# Generated by Django 5.1.3 on 2024-12-04 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prospect',
            name='valuation_reviewd_by',
        ),
    ]
