# Generated by Django 5.1.3 on 2025-01-23 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prospect',
            old_name='proof_of_payment_id',
            new_name='proof_of_payment_id_old',
        ),
        migrations.RemoveField(
            model_name='prospect',
            name='proof_of_payment',
        ),
        migrations.AddField(
            model_name='prospect',
            name='proof_of_payment_old',
            field=models.ImageField(blank=True, null=True, upload_to='prospect/proof_of_payment/', verbose_name='PROOF OF PAYMENT'),
        ),
        migrations.CreateModel(
            name='ProofofPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof_of_payment', models.ImageField(blank=True, null=True, upload_to='prospect/proof_of_payment/', verbose_name='PROOF OF PAYMENT')),
                ('proof_of_payment_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='PROOF OF PAYMENT ID')),
                ('prospect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Prospect', to='prospects.prospect')),
            ],
        ),
    ]
