# Generated by Django 5.1.3 on 2024-11-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='proof_of_payment',
            field=models.FileField(blank=True, null=True, upload_to='proof_of_payment'),
        ),
    ]
