# Generated by Django 5.1.3 on 2024-11-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0002_alter_prospect_proof_of_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='proof_of_payment',
            field=models.URLField(blank=True, null=True),
        ),
    ]
