# Generated by Django 5.1.3 on 2024-12-04 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0002_remove_prospect_valuation_reviewd_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prospect',
            name='valuation_reviewd_on',
        ),
        migrations.AddField(
            model_name='prospect',
            name='valuation_reviewd_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valuation_reviewd_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
