# Generated by Django 5.1.3 on 2025-01-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0002_rename_proof_of_payment_id_prospect_proof_of_payment_id_old_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proofofpayment',
            name='proof_of_payment',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
