# Generated by Django 5.1.3 on 2024-12-04 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0003_remove_prospect_valuation_reviewd_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='valuation_reviewd_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
