# Generated by Django 5.1.3 on 2024-11-28 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0003_alter_prospect_proof_of_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='status',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Pending', 'Pending'), ('Valuation', 'Valuation'), ('Valuation Supervisor', 'Valuation Supervisor'), ('Payment Verified', 'Payment Verified'), ('Inspection', 'Inspection'), ('Review', 'Review'), ('Pipeline', 'Pipeline'), ('Failed', 'Failed'), ('Declined', 'Declined')], default='New', max_length=20, null=True, verbose_name='STATUS'),
        ),
    ]
