# Generated by Django 5.1.3 on 2024-12-04 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0004_prospect_valuation_reviewd_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prospect',
            name='prospect_data_fields',
        ),
    ]
