# Generated by Django 5.1.3 on 2024-11-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Valuation', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleevaluationreport',
            name='accessories',
            field=models.CharField(choices=[('IN VERY BAD SHAPE', 'IN VERY BAD SHAPE'), ('IN BAD SHAPE', 'IN BAD SHAPE'), ('IN GOOD SHAPE', 'IN GOOD SHAPE'), ('IN FAIR SHAPE', 'IN FAIR SHAPE'), ('IN VERY GOOD SHAPE', 'IN VERY GOOD SHAPE'), ('IN EXCELLENT SHAPE', 'IN EXCELLENT SHAPE'), ('IN PERFECT SHAPE', 'IN PERFECT SHAPE'), ('IN NEW CONDITION', 'IN NEW CONDITION'), ('IN SHOWROOM CONDITION', 'IN SHOWROOM CONDITION')], max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicleevaluationreport',
            name='air_conditioning_system',
            field=models.CharField(choices=[('IN VERY BAD SHAPE', 'IN VERY BAD SHAPE'), ('IN BAD SHAPE', 'IN BAD SHAPE'), ('IN GOOD SHAPE', 'IN GOOD SHAPE'), ('IN FAIR SHAPE', 'IN FAIR SHAPE'), ('IN VERY GOOD SHAPE', 'IN VERY GOOD SHAPE'), ('IN EXCELLENT SHAPE', 'IN EXCELLENT SHAPE'), ('IN PERFECT SHAPE', 'IN PERFECT SHAPE'), ('IN NEW CONDITION', 'IN NEW CONDITION'), ('IN SHOWROOM CONDITION', 'IN SHOWROOM CONDITION')]),
        ),
        migrations.AlterField(
            model_name='vehicleevaluationreport',
            name='body_shell_paint',
            field=models.CharField(choices=[('IN VERY BAD SHAPE', 'IN VERY BAD SHAPE'), ('IN BAD SHAPE', 'IN BAD SHAPE'), ('IN GOOD SHAPE', 'IN GOOD SHAPE'), ('IN FAIR SHAPE', 'IN FAIR SHAPE'), ('IN VERY GOOD SHAPE', 'IN VERY GOOD SHAPE'), ('IN EXCELLENT SHAPE', 'IN EXCELLENT SHAPE'), ('IN PERFECT SHAPE', 'IN PERFECT SHAPE'), ('IN NEW CONDITION', 'IN NEW CONDITION'), ('IN SHOWROOM CONDITION', 'IN SHOWROOM CONDITION')], max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicleevaluationreport',
            name='braking_system',
            field=models.CharField(choices=[('IN VERY BAD SHAPE', 'IN VERY BAD SHAPE'), ('IN BAD SHAPE', 'IN BAD SHAPE'), ('IN GOOD SHAPE', 'IN GOOD SHAPE'), ('IN FAIR SHAPE', 'IN FAIR SHAPE'), ('IN VERY GOOD SHAPE', 'IN VERY GOOD SHAPE'), ('IN EXCELLENT SHAPE', 'IN EXCELLENT SHAPE'), ('IN PERFECT SHAPE', 'IN PERFECT SHAPE'), ('IN NEW CONDITION', 'IN NEW CONDITION'), ('IN SHOWROOM CONDITION', 'IN SHOWROOM CONDITION')]),
        ),
        migrations.AlterField(
            model_name='vehicleevaluationreport',
            name='chassis_frame',
            field=models.CharField(choices=[('IN VERY BAD SHAPE', 'IN VERY BAD SHAPE'), ('IN BAD SHAPE', 'IN BAD SHAPE'), ('IN GOOD SHAPE', 'IN GOOD SHAPE'), ('IN FAIR SHAPE', 'IN FAIR SHAPE'), ('IN VERY GOOD SHAPE', 'IN VERY GOOD SHAPE'), ('IN EXCELLENT SHAPE', 'IN EXCELLENT SHAPE'), ('IN PERFECT SHAPE', 'IN PERFECT SHAPE'), ('IN NEW CONDITION', 'IN NEW CONDITION'), ('IN SHOWROOM CONDITION', 'IN SHOWROOM CONDITION')], max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicleevaluationreport',
            name='condition_of_seats',
            field=models.CharField(choices=[('IN VERY BAD SHAPE', 'IN VERY BAD SHAPE'), ('IN BAD SHAPE', 'IN BAD SHAPE'), ('IN GOOD SHAPE', 'IN GOOD SHAPE'), ('IN FAIR SHAPE', 'IN FAIR SHAPE'), ('IN VERY GOOD SHAPE', 'IN VERY GOOD SHAPE'), ('IN EXCELLENT SHAPE', 'IN EXCELLENT SHAPE'), ('IN PERFECT SHAPE', 'IN PERFECT SHAPE'), ('IN NEW CONDITION', 'IN NEW CONDITION'), ('IN SHOWROOM CONDITION', 'IN SHOWROOM CONDITION')]),
        ),
        migrations.AlterField(
            model_name='vehicleevaluationreport',
            name='cooling_system',
            field=models.CharField(choices=[('IN VERY BAD SHAPE', 'IN VERY BAD SHAPE'), ('IN BAD SHAPE', 'IN BAD SHAPE'), ('IN GOOD SHAPE', 'IN GOOD SHAPE'), ('IN FAIR SHAPE', 'IN FAIR SHAPE'), ('IN VERY GOOD SHAPE', 'IN VERY GOOD SHAPE'), ('IN EXCELLENT SHAPE', 'IN EXCELLENT SHAPE'), ('IN PERFECT SHAPE', 'IN PERFECT SHAPE'), ('IN NEW CONDITION', 'IN NEW CONDITION'), ('IN SHOWROOM CONDITION', 'IN SHOWROOM CONDITION')]),
        ),
        migrations.AlterField(
            model_name='vehicleevaluationreport',
            name='electrical_system',
            field=models.CharField(choices=[('IN VERY BAD SHAPE', 'IN VERY BAD SHAPE'), ('IN BAD SHAPE', 'IN BAD SHAPE'), ('IN GOOD SHAPE', 'IN GOOD SHAPE'), ('IN FAIR SHAPE', 'IN FAIR SHAPE'), ('IN VERY GOOD SHAPE', 'IN VERY GOOD SHAPE'), ('IN EXCELLENT SHAPE', 'IN EXCELLENT SHAPE'), ('IN PERFECT SHAPE', 'IN PERFECT SHAPE'), ('IN NEW CONDITION', 'IN NEW CONDITION'), ('IN SHOWROOM CONDITION', 'IN SHOWROOM CONDITION')]),
        ),
        migrations.AlterField(
            model_name='vehicleevaluationreport',
            name='engine_assembly',
            field=models.CharField(choices=[('IN VERY BAD SHAPE', 'IN VERY BAD SHAPE'), ('IN BAD SHAPE', 'IN BAD SHAPE'), ('IN GOOD SHAPE', 'IN GOOD SHAPE'), ('IN FAIR SHAPE', 'IN FAIR SHAPE'), ('IN VERY GOOD SHAPE', 'IN VERY GOOD SHAPE'), ('IN EXCELLENT SHAPE', 'IN EXCELLENT SHAPE'), ('IN PERFECT SHAPE', 'IN PERFECT SHAPE'), ('IN NEW CONDITION', 'IN NEW CONDITION'), ('IN SHOWROOM CONDITION', 'IN SHOWROOM CONDITION')]),
        ),
        migrations.AlterField(
            model_name='vehicleevaluationreport',
            name='gearbox_assembly',
            field=models.CharField(choices=[('IN VERY BAD SHAPE', 'IN VERY BAD SHAPE'), ('IN BAD SHAPE', 'IN BAD SHAPE'), ('IN GOOD SHAPE', 'IN GOOD SHAPE'), ('IN FAIR SHAPE', 'IN FAIR SHAPE'), ('IN VERY GOOD SHAPE', 'IN VERY GOOD SHAPE'), ('IN EXCELLENT SHAPE', 'IN EXCELLENT SHAPE'), ('IN PERFECT SHAPE', 'IN PERFECT SHAPE'), ('IN NEW CONDITION', 'IN NEW CONDITION'), ('IN SHOWROOM CONDITION', 'IN SHOWROOM CONDITION')]),
        ),
        migrations.AlterField(
            model_name='vehicleevaluationreport',
            name='steering_system',
            field=models.CharField(choices=[('IN VERY BAD SHAPE', 'IN VERY BAD SHAPE'), ('IN BAD SHAPE', 'IN BAD SHAPE'), ('IN GOOD SHAPE', 'IN GOOD SHAPE'), ('IN FAIR SHAPE', 'IN FAIR SHAPE'), ('IN VERY GOOD SHAPE', 'IN VERY GOOD SHAPE'), ('IN EXCELLENT SHAPE', 'IN EXCELLENT SHAPE'), ('IN PERFECT SHAPE', 'IN PERFECT SHAPE'), ('IN NEW CONDITION', 'IN NEW CONDITION'), ('IN SHOWROOM CONDITION', 'IN SHOWROOM CONDITION')]),
        ),
        migrations.AlterField(
            model_name='vehicleevaluationreport',
            name='suspension',
            field=models.CharField(choices=[('IN VERY BAD SHAPE', 'IN VERY BAD SHAPE'), ('IN BAD SHAPE', 'IN BAD SHAPE'), ('IN GOOD SHAPE', 'IN GOOD SHAPE'), ('IN FAIR SHAPE', 'IN FAIR SHAPE'), ('IN VERY GOOD SHAPE', 'IN VERY GOOD SHAPE'), ('IN EXCELLENT SHAPE', 'IN EXCELLENT SHAPE'), ('IN PERFECT SHAPE', 'IN PERFECT SHAPE'), ('IN NEW CONDITION', 'IN NEW CONDITION'), ('IN SHOWROOM CONDITION', 'IN SHOWROOM CONDITION')]),
        ),
        migrations.AlterField(
            model_name='vehicleevaluationreport',
            name='transmission_system',
            field=models.CharField(choices=[('IN VERY BAD SHAPE', 'IN VERY BAD SHAPE'), ('IN BAD SHAPE', 'IN BAD SHAPE'), ('IN GOOD SHAPE', 'IN GOOD SHAPE'), ('IN FAIR SHAPE', 'IN FAIR SHAPE'), ('IN VERY GOOD SHAPE', 'IN VERY GOOD SHAPE'), ('IN EXCELLENT SHAPE', 'IN EXCELLENT SHAPE'), ('IN PERFECT SHAPE', 'IN PERFECT SHAPE'), ('IN NEW CONDITION', 'IN NEW CONDITION'), ('IN SHOWROOM CONDITION', 'IN SHOWROOM CONDITION')]),
        ),
        migrations.AlterField(
            model_name='vehicleevaluationreport',
            name='tyre_condition',
            field=models.CharField(choices=[('IN VERY BAD SHAPE', 'IN VERY BAD SHAPE'), ('IN BAD SHAPE', 'IN BAD SHAPE'), ('IN GOOD SHAPE', 'IN GOOD SHAPE'), ('IN FAIR SHAPE', 'IN FAIR SHAPE'), ('IN VERY GOOD SHAPE', 'IN VERY GOOD SHAPE'), ('IN EXCELLENT SHAPE', 'IN EXCELLENT SHAPE'), ('IN PERFECT SHAPE', 'IN PERFECT SHAPE'), ('IN NEW CONDITION', 'IN NEW CONDITION'), ('IN SHOWROOM CONDITION', 'IN SHOWROOM CONDITION')]),
        ),
        migrations.AlterField(
            model_name='vehicleevaluationreport',
            name='wheels',
            field=models.CharField(choices=[('IN VERY BAD SHAPE', 'IN VERY BAD SHAPE'), ('IN BAD SHAPE', 'IN BAD SHAPE'), ('IN GOOD SHAPE', 'IN GOOD SHAPE'), ('IN FAIR SHAPE', 'IN FAIR SHAPE'), ('IN VERY GOOD SHAPE', 'IN VERY GOOD SHAPE'), ('IN EXCELLENT SHAPE', 'IN EXCELLENT SHAPE'), ('IN PERFECT SHAPE', 'IN PERFECT SHAPE'), ('IN NEW CONDITION', 'IN NEW CONDITION'), ('IN SHOWROOM CONDITION', 'IN SHOWROOM CONDITION')]),
        ),
        migrations.AlterField(
            model_name='vehicleevaluationreport',
            name='windshield',
            field=models.CharField(choices=[('IN VERY BAD SHAPE', 'IN VERY BAD SHAPE'), ('IN BAD SHAPE', 'IN BAD SHAPE'), ('IN GOOD SHAPE', 'IN GOOD SHAPE'), ('IN FAIR SHAPE', 'IN FAIR SHAPE'), ('IN VERY GOOD SHAPE', 'IN VERY GOOD SHAPE'), ('IN EXCELLENT SHAPE', 'IN EXCELLENT SHAPE'), ('IN PERFECT SHAPE', 'IN PERFECT SHAPE'), ('IN NEW CONDITION', 'IN NEW CONDITION'), ('IN SHOWROOM CONDITION', 'IN SHOWROOM CONDITION')]),
        ),
    ]
