# Generated by Django 5.1.3 on 2024-11-28 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Valuation', '0003_alter_vehicleevaluationreport_accessories_and_more'),
        ('prospects', '0003_alter_prospect_proof_of_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleInspectionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_reg_number', models.CharField(max_length=50)),
                ('inspector', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('reason_for_inspection', models.CharField()),
                ('ignition_status', models.CharField()),
                ('ignition_comment', models.TextField()),
                ('wind_shield_wipers_status', models.CharField()),
                ('wind_shield_wipers_comment', models.TextField()),
                ('headlights_status', models.CharField()),
                ('headlights_comment', models.TextField()),
                ('turn_signals_status', models.CharField()),
                ('turn_signals_comment', models.TextField()),
                ('brake_lights_status', models.CharField()),
                ('brake_lights_comment', models.TextField()),
                ('side_mirrors_status', models.CharField()),
                ('side_mirrors_comment', models.TextField()),
                ('horn_status', models.CharField()),
                ('horn_comment', models.TextField()),
                ('radio_status', models.CharField()),
                ('radio_comment', models.TextField()),
                ('body_condition_status', models.CharField()),
                ('body_condition_comment', models.TextField()),
                ('exterior_flashlights_status', models.CharField()),
                ('exterior_flashlights_comment', models.TextField()),
                ('windows_status', models.CharField()),
                ('windows_comment', models.TextField()),
                ('any_other_abnormalities_status', models.CharField()),
                ('any_other_abnormalities_comment', models.TextField()),
                ('remarks', models.TextField()),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prospects.prospect')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Valuation.vehicleasset')),
            ],
        ),
    ]
