# Generated by Django 5.1.3 on 2025-01-23 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Valuation', '0003_vehicleasset_vehicle_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleevaluationreport',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vehicleasset',
            name='maketypes',
            field=models.CharField(blank=True, choices=[('ACURA', 'ACURA'), ('ALFA_ROMEO', 'ALFA ROMEO'), ('AUDI', 'AUDI'), ('BMW', 'BMW'), ('BUICK', 'BUICK'), ('CADILLAC', 'CADILLAC'), ('CHEVROLET', 'CHEVROLET'), ('CHRYSLER', 'CHRYSLER'), ('CITROEN', 'CITROËN'), ('DODGE', 'DODGE'), ('FERRARI', 'FERRARI'), ('FIAT', 'FIAT'), ('FORD', 'FORD'), ('GMC', 'GMC'), ('HONDA', 'HONDA'), ('HYUNDAI', 'HYUNDAI'), ('JAGUAR', 'JAGUAR'), ('JEEP', 'JEEP'), ('KIA', 'KIA'), ('LAND_ROVER', 'LAND ROVER'), ('LEXUS', 'LEXUS'), ('LINCOLN', 'LINCOLN'), ('MASERATI', 'MASERATI'), ('MAZDA', 'MAZDA'), ('MCLAREN', 'MCLAREN'), ('MERCEDES_BENZ', 'MERCEDES-BENZ'), ('MITSUBISHI', 'MITSUBISHI'), ('NISSAN', 'NISSAN'), ('PAGANI', 'PAGANI'), ('PEUGEOT', 'PEUGEOT'), ('PORSCHE', 'PORSCHE'), ('RAM', 'RAM'), ('RENAULT', 'RENAULT'), ('ROLLS_ROYCE', 'ROLLS-ROYCE'), ('SAAB', 'SAAB'), ('SUBARU', 'SUBARU'), ('SUZUKI', 'SUZUKI'), ('TESLA', 'TESLA'), ('TOYOTA', 'TOYOTA'), ('VOLKSWAGEN', 'VOLKSWAGEN'), ('SINO TRUCK HOWO', 'SINO TRUCK HOWO'), ('VOLVO', 'VOLVO'), ('OTHER', 'OTHER')], max_length=50, null=True, verbose_name='Car Make Type'),
        ),
        migrations.AlterField(
            model_name='vehicleevaluationreport',
            name='body_description',
            field=models.CharField(choices=[('SALOON', 'SALOON'), ('SUV', 'SUV'), ('VAN', 'VAN'), ('STATION WAGON', 'STATION WAGON'), ('MINI-VAN', 'MINI-VAN'), ('SEDAN', 'SEDAN'), ('COUPE', 'COUPE'), ('CROSS-OVERS', 'CROSS-OVERS'), ('HATCH BACK', 'HATCH BACK'), ('TRUCK', 'TRUCK'), ('PICK UP DOUBLE CABIN', 'PICK UP DOUBLE CABIN'), ('PICK UP SINGLE CABIN', 'PICK UP SINGLE CABIN')], max_length=200, null=True, verbose_name='body description'),
        ),
        migrations.AlterField(
            model_name='vehicleevaluationreport',
            name='maketypes',
            field=models.CharField(blank=True, choices=[('ACURA', 'ACURA'), ('ALFA_ROMEO', 'ALFA ROMEO'), ('AUDI', 'AUDI'), ('BMW', 'BMW'), ('BUICK', 'BUICK'), ('CADILLAC', 'CADILLAC'), ('CHEVROLET', 'CHEVROLET'), ('CHRYSLER', 'CHRYSLER'), ('CITROEN', 'CITROËN'), ('DODGE', 'DODGE'), ('FERRARI', 'FERRARI'), ('FIAT', 'FIAT'), ('FORD', 'FORD'), ('GMC', 'GMC'), ('HONDA', 'HONDA'), ('HYUNDAI', 'HYUNDAI'), ('JAGUAR', 'JAGUAR'), ('JEEP', 'JEEP'), ('KIA', 'KIA'), ('LAND_ROVER', 'LAND ROVER'), ('LEXUS', 'LEXUS'), ('LINCOLN', 'LINCOLN'), ('MASERATI', 'MASERATI'), ('MAZDA', 'MAZDA'), ('MCLAREN', 'MCLAREN'), ('MERCEDES_BENZ', 'MERCEDES-BENZ'), ('MITSUBISHI', 'MITSUBISHI'), ('NISSAN', 'NISSAN'), ('PAGANI', 'PAGANI'), ('PEUGEOT', 'PEUGEOT'), ('PORSCHE', 'PORSCHE'), ('RAM', 'RAM'), ('RENAULT', 'RENAULT'), ('ROLLS_ROYCE', 'ROLLS-ROYCE'), ('SAAB', 'SAAB'), ('SUBARU', 'SUBARU'), ('SUZUKI', 'SUZUKI'), ('TESLA', 'TESLA'), ('TOYOTA', 'TOYOTA'), ('VOLKSWAGEN', 'VOLKSWAGEN'), ('SINO TRUCK HOWO', 'SINO TRUCK HOWO'), ('VOLVO', 'VOLVO'), ('OTHER', 'OTHER')], max_length=50, null=True, verbose_name='Car Make Type'),
        ),
    ]
