# Generated by Django 5.1.3 on 2024-11-29 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Valuation', '0004_vehicleinspectionreport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicleinspectionreport',
            old_name='client_name',
            new_name='prospect',
        ),
        migrations.RemoveField(
            model_name='vehicleinspectionreport',
            name='vehicle_reg_number',
        ),
    ]
