# Generated by Django 5.1.3 on 2025-01-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Valuation', '0004_vehicleevaluationreport_is_draft_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleevaluationreport',
            name='is_draft',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
