# Generated by Django 5.1.3 on 2025-01-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Valuation', '0005_alter_vehicleevaluationreport_is_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleevaluationreport',
            name='is_draft',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
