# Generated by Django 5.1.3 on 2024-11-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Valuation', '0005_rename_client_name_vehicleinspectionreport_prospect_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleasset',
            name='status',
            field=models.CharField(choices=[('NOT VALUED', 'NOT VALUED'), ('VALUED', 'VALUED'), ('INSPECTION REQUIRED', 'INSPECTION REQUIRED'), ('INSPECTED', 'INSPECTED'), ('IN TRACKING', 'IN TRACKING'), ('UNPOCESSED', 'UNPOCESSED'), ('REPOSESSED', 'REPOSESSED'), ('IMPOUNDED', 'IMPOUNDED'), ('SELF_PARKED', 'SELF_PARKED'), ('RECLAIMED', 'RECLAIMED'), ('DISPOSED_OFF', 'DISPOSED_OFF')], default='NOT VALUED', verbose_name='Status'),
        ),
    ]
