# Generated by Django 5.1.3 on 2025-01-23 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Valuation', '0003_alter_vehicleasset_maketypes_and_more'),
        ('Valuation', '0006_alter_vehicleevaluationreport_is_draft'),
    ]

    operations = [
    ]
