# Generated by Django 5.1.3 on 2025-01-25 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Valuation', '0007_merge_20250123_1748'),
        ('Valuation', '0009_alter_vehicleevaluationreport_accessories_and_more'),
    ]

    operations = [
    ]
